CREATE TABLE HOSPEDE(
	COD_HOSP SERIAL PRIMARY KEY,
	DT_NASC DATE NOT NULL,
	NOME VARCHAR(50) NOT NULL
)

CREATE TABLE FUNCIONARIO(
	COD_FUNC SERIAL PRIMARY KEY,
	DT_NASC DATE NOT NULL,
	NOME VARCHAR(50) NOT NULL
)

CREATE TABLE CATEGORIA(
	COD_CAT SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	PRECO FLOAT NOT NULL
)

CREATE TABLE APARTAMENTO(
	NUM_AP INT PRIMARY KEY,
	COD_CAT INT NOT NULL,
	FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA (COD_CAT)
)

CREATE TABLE HOSPEDAGEM(
	COD_HOSPEDAGEM SERIAL PRIMARY KEY,
	DT_ENT DATE NOT NULL,
	DT_SAIDA DATE,
	COD_HOSP INT NOT NULL,
	NUM_AP INT NOT NULL,
	COD_FUNC INT NOT NULL,
	FOREIGN KEY (COD_HOSP) REFERENCES HOSPEDE (COD_HOSP),
	FOREIGN KEY (NUM_AP) REFERENCES APARTAMENTO (NUM_AP),
	FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO (COD_FUNC)
)