--- Exercicio ---

-- 1)
SELECT NOME FROM CATEGORIA WHERE PRECO > 100 AND PRECO < 200;
--2)
SELECT NOME FROM CATEGORIA WHERE NOME ILIKE '%LUXO%'
--3)
SELECT NUM_AP FROM HOSPEDAGEM WHERE DT_SAIDA IS NULL
--4)
SELECT NUM_AP FROM APARTAMENTO WHERE COD_CAT IN (1,2,3,11,34,54,24,12)
--5)
SELECT * FROM APARTAMENTO AS APT, CATEGORIA AS CAT WHERE APT.COD_CAT=CAT.COD_CAT AND (NOME ILIKE 'LUXO%')
--6)
SELECT COUNT(*) AS "QUANTIDADE DE APARTAMENTOS" FROM APARTAMENTO
--7)
SELECT SUM(PRECO) AS "SOMATÓRIO DOS PREÇOS DE CATEGORIA" FROM CATEGORIA
--8)
SELECT AVG(PRECO) AS "MÉDIA DOS PREÇOS DAS CATEGORIAS" FROM CATEGORIA
--9)
SELECT MAX(PRECO) AS "MAIOR PREÇO DE CATEGORIA" FROM CATEGORIA
--10)
SELECT MIN(PRECO) AS "MENOR PREÇO DE CATEGORIA" FROM CATEGORIA
--11)
SELECT NOME AS "NASCIDOS APÓS 1° DE JANEIRO DE 1970" FROM HOSPEDE WHERE DT_NASC > '1970-01-01'
--12)
SELECT COUNT(*) AS "QUANTIDADE DE HOSPEDES" FROM HOSPEDE
--13)
ALTER TABLE HOSPEDE ADD COLUMN NACIONALIDADE VARCHAR(100) NOT NULL DEFAULT 'NÃO INFORMADO'
--14)
SELECT DT_NASC AS "DATA DE NASCIMENTO DO HOSPEDE MAIS VELHO" FROM HOSPEDE WHERE DT_NASC = ( SELECT MIN(DT_NASC) FROM HOSPEDE)
--15)
SELECT DT_NASC AS "DATA DE NASCIMENTO DO HOSPEDE MAIS NOVO" FROM HOSPEDE WHERE DT_NASC = (SELECT MAX(DT_NASC) FROM HOSPEDE)
--16)
SELECT NOME AS "HOSPEDE MAIS VELHO" FROM HOSPEDE WHERE DT_NASC = (SELECT MIN(DT_NASC) FROM HOSPEDE)
--17)
UPDATE CATEGORIA SET PRECO = PRECO * 1.1
--18)
SELECT NUM_AP FROM HOSPEDAGEM WHERE COD_HOSP = (SELECT COD_HOSP FROM HOSPEDE WHERE NOME ILIKE 'JOÃO')
--19)
SELECT NOME FROM HOSPEDE AS H JOIN HOSPEDAGEM AS HO ON H.COD_HOSP=HO.COD_HOSP WHERE (HO.NUM_AP<>201 OR NUM_AP IS NULL)
--20)
SELECT H.NOME, CAT.NOME FROM HOSPEDE AS H, HOSPEDAGEM AS HO, APARTAMENTO AS APT, CATEGORIA AS CAT
WHERE (H.COD_HOSP=HO.COD_HOSP AND HO.NUM_AP=APT.NUM_AP AND APT.COD_CAT=CAT.COD_CAT)
AND (CAT.NOME NOT ILIKE 'LUXO')
--21)
SELECT H.NOME AS "HOSPEDE"
FROM HOSPEDE AS H JOIN HOSPEDAGEM AS HO ON H.COD_HOSP=HO.COD_HOSP JOIN FUNCIONARIO AS FUNC ON HO.COD_FUNC=FUNC.COD_FUNC
WHERE (FUNC.DT_NASC = (SELECT MAX(DT_NASC) FROM FUNCIONARIO)) AND H.DT_NASC = (SELECT MIN(DT_NASC) FROM HOSPEDE)
--22)
