--- EXERCICIO 2 ---

--1)
SELECT NOME, DT_NASC AS "DATA DE NASCIMENTO" FROM HOSPEDE ORDER BY NOME ASC, DT_NASC DESC
--2)
SELECT NOME AS "CATEGORIA" FROM CATEGORIA ORDER BY NOME ASC
--3)
SELECT PRECO, NUM_AP FROM APARTAMENTO NATURAL JOIN CATEGORIA
--4)
SELECT NOME, COUNT(APT.NUM_AP)
FROM CATEGORIA AS CAT JOIN APARTAMENTO AS APT ON CAT.COD_CAT=APT.COD_CAT
GROUP BY NOME
--5)
SELECT NOME, EXTRACT(MONTH FROM DT_NASC) AS "MÊS DE NASCIMENTO", EXTRACT(YEAR FROM DT_NASC) AS "ANO DE NASCIMENTO"
FROM HOSPEDE WHERE NACIONALIDADE ILIKE 'BRASILEIR%'
ORDER BY DT_NASC DESC, NOME ASC
--6)
SELECT H.NOME, NUM_AP AS APARTAMENTO, COUNT(NUM_AP) AS QUANTIDADE
FROM HOSPEDE AS H LEFT JOIN HOSPEDAGEM AS HO ON H.COD_HOSP=HO.COD_HOSP
GROUP BY H.NOME, NUM_AP
ORDER BY QUANTIDADE DESC
--7)
SELECT * FROM CATEGORIA WHERE LENGTH(NOME) > 15
--8)
SELECT NUM_AP, NOME
FROM HOSPEDAGEM NATURAL JOIN APARTAMENTO NATURAL JOIN CATEGORIA
WHERE (EXTRACT(YEAR FROM DT_ENT) = 2017)
--11)
SELECT FUNC.COD_FUNC, (COUNT(FUNC.COD_FUNC)*10 + SALARIO) AS "SALARIO COM BÔNUS"
FROM FUNCIONARIO AS FUNC LEFT JOIN HOSPEDAGEM AS HO ON FUNC.COD_FUNC=HO.COD_FUNC
GROUP BY FUNC.COD_FUNC, SALARIO
ORDER BY FUNC.COD_FUNC
--12)
SELECT NOME, COUNT(NUM_AP)
FROM APARTAMENTO AS APT RIGHT JOIN CATEGORIA AS CAT ON CAT.COD_CAT=APT.COD_CAT
GROUP BY NOME
ORDER BY NOME, COUNT(NUM_AP)
--13)

--14)
SELECT FUNC.NOME
FROM FUNCIONARIO AS FUNC, HOSPEDE AS H, HOSPEDAGEM AS HO, APARTAMENTO AS APT, CATEGORIA AS CAT
WHERE (FUNC.COD_FUNC=HO.COD_FUNC AND H.COD_HOSP=HO.COD_HOSP AND APT.NUM_AP=HO.NUM_AP AND APT.COD_CAT=CAT.COD_CAT)
AND (H.NOME ILIKE 'JOÃO%' OR CAT.NOME='LUXO')
--15)









