-- TRIGGER PARA ALTERAR O ESTADO DE LIVRE DE UM APARTAMENTO
---- FUNCAO
CREATE OR REPLACE FUNCTION FC_APARTAMENTO_ATUALIZA_LIVRE()
RETURNS TRIGGER AS $$
BEGIN
	IF NEW.DT_SAIDA < NEW.DT_ENT
		THEN RAISE EXCEPTION 'DATA DE SAIDA DEVE SER MAIOR QUE DATA DE ENTRADA';
	END IF;

	IF (TG_OP LIKE 'INSERT' AND (SELECT LIVRE FROM APARTAMENTO WHERE NUM_AP=NEW.NUM_AP)=FALSE)
		THEN RAISE EXCEPTION 'APARTAMENTO % NÃO ESTÁ LIVRE', NEW.NUM_AP;
	END IF;

	IF NEW.DT_SAIDA IS NULL
		THEN UPDATE APARTAMENTO SET LIVRE=FALSE WHERE NUM_AP=NEW.NUM_AP;
		RAISE INFO 'APARTAMENTO % NÃO ESTÁ MAIS LIVRE', NEW.NUM_AP;
	ELSE
		UPDATE APARTAMENTO SET LIVRE=TRUE WHERE NUM_AP=NEW.NUM_AP;
		RAISE INFO 'APARTAMENTO % AGORA ESTÁ LIVRE', NEW.NUM_AP;
	END IF;

	RETURN NEW;
END
$$ LANGUAGE PLPGSQL;

---- TRIGGER
CREATE OR REPLACE TRIGGER TG_HOSPEDAGEM_BEFORE_INSERT_UPDATE
BEFORE INSERT OR UPDATE 
ON HOSPEDAGEM
FOR EACH ROW
EXECUTE FUNCTION FC_APARTAMENTO_ATUALIZA_LIVRE();

--





