-- CRIANDO UMA VIEW --
CREATE VIEW FUNC_TODOS AS SELECT * FROM FUNCIONARIO
--- APAGANDO UMA VIEW
DROP VIEW FUNC_TODOS

--- MÚLTIPLAS TABELAS
CREATE VIEW HOSPEDAGENS_CARLOS AS SELECT * FROM HOSPEDAGEM WHERE COD_FUNC = (SELECT COD_FUNC FROM FUNCIONARIO WHERE NOME ILIKE 'CARLOS');

--- MAIS DE UMA TABELA NA VIEW
CREATE VIEW HO_FUNC AS SELECT * FROM HOSPEDAGEM NATURAL JOIN FUNCIONARIO
--- SOBREPOSIÇÃO DE VIEW
CREATE OR REPLACE VIEW HOSPEDAGENS_CARLOS AS SELECT * FROM HOSPEDAGEM NATURAL JOIN FUNCIONARIO WHERE (NOME ILIKE 'CARLOS') AND (EXTRACT(MONTH FROM DT_ENT) = 04); 

-- ACESSO RESTRINGIDOS A INFORMAÇẼOS DE TABELAS
CREATE VIEW PUBLIC_HOSPEDE AS SELECT NOME, NACIONALIDADE FROM HOSPEDE

-- VIEWS MATERIALIZADAS
CREATE MATERIALIZED VIEW CATEGORIA_MATERIALIZADA AS SELECT NOME, PRECO FROM CATEGORIA
--- ATUALIZAR VIEWS MATERIALIZADAS
REFRESH MATERIALIZED VIEW CATEGORIA_MATERIALIZADA