@startuml Emprestimo-Livro

class Livro{
    - titulo: string
    - ano: int
    - codigo: string
    + getTitulo(): string
    + getAno(): int
    + getCodigo(): string
}

class Autor{
    - nome: string
    - nacionalidade: string
    + getNome(): string
    + getNacionalidade(): string
}

class Emprestimo{
    - dataEmprestimo: date
    - dataDevolucao: date
    + getDataEmprestimo: date
    + getDataDevolucao: date
}

Livro --|> Autor:"é escrito por" (0..N)
Livro --|> Emprestimo: "pode ser emprestado" (1..N)
Emprestimo --|> Livro: " " (N..1)

@enduml