' Crie um diagrama de classe para um sistema de estacionamento. Considere os seguintes pontos:
' O estacionamento possui um nome e uma capacidade máxima.
' Cada vaga tem um número único e está associada a um tipo (por exemplo, vaga para carro, moto, etc.).
' O cliente utiliza o estacionamento e tem nome, CPF e placa do veículo.
' O estacionamento tem um registro de entrada e saída de veículos, com data e hora de cada evento.
' Um veículo pode ser estacionado em uma vaga por um tempo determinado.
' Considere que:
' Um Estacionamento pode ter várias Vagas.
' Um Veículo pode ser associado a vários Registros, mas um Registro está relacionado a apenas um Veículo e uma Vaga.
' Um Cliente pode ter vários Veículos.

@startuml Gestao-estacionamento
title Sistema de Gestão de Estacionamento

' Classes

class Estacionamento{
    - nome: string
    - capacidadeMaxima: int
}

class Vaga{
    - estacionamento: Estacionamento
    - numeroUnico: int
    - tipo: string
}

class Cliente{
    - nome: string
    - CPF: string
}

class Veiculo{
    - placa: string
    - cliente: Cliente
}

class Registro{
    - veiculo: Veiculo
    - vaga: Vaga
    - entrada: DateTime
    - saida: DateTime
}

' Relacionamentos
Estacionamento "1..1" -- "1..N" Vaga: possui
Cliente "1..1" -- "1..N" Veiculo: possui

Registro "1..N" -- "1..1" Veiculo
Registro "1..N" -- "1..1" Vaga

@enduml