' Sistema de Cadastro de Funcionários
' Por meio do Diagrama de Classe, modelar um sistema de cadastro de funcionários para uma empresa.
' O sistema deve gerenciar diferentes tipos de funcionários (por exemplo, Funcionário e Gerente) e suas informações pessoais e profissionais.
' A empresa tem um departamento de RH que gerencia os funcionários.
' Cada funcionário possui um nome, CPF, cargo e salário.
' Além disso, os funcionários podem ser gerentes de equipes, e um gerente tem um departamento específico sob sua responsabilidade.

@startuml Cadastro-Funcionarios
title Cadastro de funcionários

' Classes

class Funcionario{
    - CPF: string
    - cargo: string
    - salario: float
}

class Gerente{
    - codDepartamento: string

    + getCodDepartamento(): string
}

class FuncionarioRH{
    + cadastrarFuncionario(funcionario: Funcionario): void
}

class Departamento{
    - codDepartamento: string

    + getCodDepartamento(): string
}

' Herança
Funcionario <|-- Gerente
Funcionario <|-- FuncionarioRH
Funcionario <|-- Atendente

' Relacionamento
Gerente "1..1" -- "1..1" Departamento: gerencia

@enduml