-- CREATE TABLES
CREATE TABLE TITULO(
	COD_TITULO SERIAL PRIMARY KEY,
	NOME VARCHAR(100),
	DESCRICAO VARCHAR(100)
);

CREATE TABLE LIVRO(
	COD_LIVRO SERIAL PRIMARY KEY,
	COD_TITULO INT,
	VALOR FLOAT,
	ESTOQUE INT,

	FOREIGN KEY (COD_TITULO) REFERENCES TITULO(COD_TITULO)
);

CREATE TABLE FORNECEDOR(
	COD_FORNECEDOR SERIAL PRIMARY KEY,
	NOME VARCHAR(50),
	FONE VARCHAR(100)
);

CREATE TABLE PEDIDO(
	COD_PEDIDO SERIAL PRIMARY KEY,
	COD_FORNECEDOR INT,
	HORA TIME,
	DATA_PEDIDO DATE,
	VALOR_TOTAL FLOAT,
	
	FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE TABLE ITEM_PEDIDO(
	COD_ITEM_PEDIDO SERIAL PRIMARY KEY,
	COD_PEDIDO INT,
	COD_LIVRO INT,

	FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO(COD_PEDIDO),
	FOREIGN KEY (COD_LIVRO) REFERENCES LIVRO(COD_LIVRO)
);

CREATE TABLE CONTROLE_DE_ALTERACAO(
	OPERACAO VARCHAR(1),
	DATA_HORA TIMESTAMP,
	USUARIO_QUE_ALTEROU VARCHAR(100),
	COD_ANTIGO INT,
	COD_NOVO INT,
	ESTOQUE_ANTIGO INT
);





