-- TRIGGERS

--- CRIANDO A FUNCAO
CREATE OR REPLACE FUNCTION FUNCAO_CONTROLA_ITEM()
RETURNS TRIGGER AS $$
BEGIN
	UPDATE LIVRO SET
	ESTOQUE = ESTOQUE - NEW.ESTOQUE
	WHERE COD_LIVRO = NEW.COD_LIVRO;

	UPDATE PEDIDO SET
	VALOR_TOTAL = VALOR_TOTAL + NEW.VALOR_TOTAL
	WHERE COD_PEDIDO = NEW.COD_PEDIDO;

	RETURN NEW;
END
$$ LANGUAGE PLPGSQL;

--- CRIANDO O TRIGGER
CREATE TRIGGER CONTROLA_ITEM
BEFORE INSERT OR DELETE OR UPDATE
ON ITEM_PEDIDO
FOR EACH ROW
EXECUTE FUNCTION FUNCAO_CONTROLA_ITEM();